apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: thshifts
  namespace: thinkon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: thshifts
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
